import type { HeightmapTool } from './heightmapTools.ts';
import * as tools from './heightmapTools.ts';

export interface HeightmapTemplate {
  id: number;
  name: string;
  steps: HeightmapTool[];
  probability: number;
}

export const heightmapTemplates: Record<string, HeightmapTemplate> = {
  volcano: {
    id: 0,
    name: 'Volcano',
    steps: [
      tools.hill({
        count: 1,
        height: { from: 90, to: 100 },
        rangeX: { from: 44, to: 56 },
        rangeY: { from: 40, to: 60 },
      }),
      tools.multiply({
        multiplier: 0.8,
        range: { from: 50, to: 100 },
      }),
      tools.range({
        count: 1.5,
        height: { from: 30, to: 55 },
        rangeX: { from: 45, to: 55 },
        rangeY: { from: 40, to: 60 },
      }),
      tools.smooth({
        power: 3,
      }),
      tools.hill({
        count: 1.5,
        height: { from: 35, to: 45 },
        rangeX: { from: 25, to: 30 },
        rangeY: { from: 20, to: 75 },
      }),
      tools.hill({
        count: 1,
        height: { from: 35, to: 55 },
        rangeX: { from: 75, to: 80 },
        rangeY: { from: 25, to: 75 },
      }),
      tools.hill({
        count: 0.5,
        height: { from: 20, to: 25 },
        rangeX: { from: 10, to: 15 },
        rangeY: { from: 20, to: 25 },
      }),
      tools.mask({
        power: 3,
      }),
    ],
    probability: 3,
  },
  highIsland: {
    id: 1,
    name: 'High Island',
    steps: [
      tools.hill({
        count: 1,
        height: { from: 90, to: 100 },
        rangeX: { from: 65, to: 75 },
        rangeY: { from: 47, to: 53 },
      }),
      tools.add({
        add: 7,
        range: 'all',
      }),
      tools.hill({
        count: { from: 5, to: 6 },
        height: { from: 20, to: 30 },
        rangeX: { from: 25, to: 55 },
        rangeY: { from: 45, to: 55 },
      }),
      tools.range({
        count: 1,
        height: { from: 40, to: 50 },
        rangeX: { from: 45, to: 55 },
        rangeY: { from: 45, to: 55 },
      }),
      tools.multiply({ multiplier: 0.8, range: 'land' }),
      tools.mask({ power: 3 }),
      tools.smooth({ power: 2 }),
      tools.through({
        count: { from: 2, to: 3 },
        height: { from: 20, to: 30 },
        rangeX: { from: 20, to: 30 },
        rangeY: { from: 20, to: 30 },
      }),
      tools.through({
        count: { from: 2, to: 3 },
        height: { from: 20, to: 30 },
        rangeX: { from: 60, to: 80 },
        rangeY: { from: 70, to: 80 },
      }),
      tools.hill({
        count: 1,
        height: { from: 10, to: 15 },
        rangeX: { from: 60, to: 60 },
        rangeY: { from: 50, to: 50 },
      }),
      tools.hill({
        count: 1.5,
        height: { from: 13, to: 16 },
        rangeX: { from: 15, to: 20 },
        rangeY: { from: 20, to: 75 },
      }),
      tools.range({
        count: 1.5,
        height: { from: 30, to: 40 },
        rangeX: { from: 15, to: 85 },
        rangeY: { from: 30, to: 40 },
      }),
      tools.range({
        count: 1.5,
        height: { from: 30, to: 40 },
        rangeX: { from: 15, to: 85 },
        rangeY: { from: 60, to: 70 },
      }),
      tools.pit({
        count: { from: 3, to: 5 },
        height: { from: 10, to: 30 },
        rangeX: { from: 15, to: 85 },
        rangeY: { from: 20, to: 80 },
      }),
    ],
    probability: 19,
  },
  lowIsland: {
    id: 2,
    name: 'Low Island',
    steps: [
      tools.hill({
        count: 1,
        height: { from: 90, to: 99 },
        rangeX: { from: 60, to: 80 },
        rangeY: { from: 45, to: 55 },
      }),
      tools.hill({
        count: { from: 1, to: 2 },
        height: { from: 20, to: 30 },
        rangeX: { from: 10, to: 30 },
        rangeY: { from: 10, to: 90 },
      }),
      tools.smooth({ power: 2 }),
      tools.hill({
        count: { from: 6, to: 7 },
        height: { from: 25, to: 35 },
        rangeX: { from: 20, to: 70 },
        rangeY: { from: 30, to: 70 },
      }),
      tools.range({
        count: 1,
        height: { from: 40, to: 50 },
        rangeX: { from: 45, to: 55 },
        rangeY: { from: 45, to: 55 },
      }),
      tools.through({
        count: { from: 2, to: 3 },
        height: { from: 20, to: 30 },
        rangeX: { from: 15, to: 85 },
        rangeY: { from: 20, to: 30 },
      }),
      tools.through({
        count: { from: 2, to: 3 },
        height: { from: 20, to: 30 },
        rangeX: { from: 15, to: 85 },
        rangeY: { from: 70, to: 80 },
      }),
      tools.hill({
        count: 1.5,
        height: { from: 10, to: 15 },
        rangeX: { from: 5, to: 15 },
        rangeY: { from: 20, to: 80 },
      }),
      tools.hill({
        count: 1,
        height: { from: 10, to: 15 },
        rangeX: { from: 85, to: 95 },
        rangeY: { from: 70, to: 80 },
      }),
      tools.pit({
        count: { from: 5, to: 7 },
        height: { from: 15, to: 20 },
        rangeX: { from: 15, to: 85 },
        rangeY: { from: 20, to: 80 },
      }),
      tools.multiply({
        multiplier: 0.4,
        range: { from: 20, to: 100 },
      }),
      tools.mask({ power: 4 }),
    ],
    probability: 9,
  },
  continents: {
    id: 3,
    name: 'Continents',
    steps: [
      tools.hill({
        count: 1,
        height: { from: 80, to: 85 },
        rangeX: { from: 60, to: 80 },
        rangeY: { from: 40, to: 60 },
      }),
      tools.hill({
        count: 1,
        height: { from: 80, to: 85 },
        rangeX: { from: 20, to: 30 },
        rangeY: { from: 40, to: 60 },
      }),
      tools.hill({
        count: { from: 6, to: 7 },
        height: { from: 15, to: 30 },
        rangeX: { from: 25, to: 75 },
        rangeY: { from: 15, to: 85 },
      }),
      tools.multiply({ multiplier: 0.6, range: 'land' }),
      tools.hill({
        count: { from: 8, to: 10 },
        height: { from: 5, to: 10 },
        rangeX: { from: 15, to: 85 },
        rangeY: { from: 20, to: 80 },
      }),
      tools.range({
        count: { from: 1, to: 2 },
        height: { from: 30, to: 60 },
        rangeX: { from: 5, to: 15 },
        rangeY: { from: 25, to: 75 },
      }),
      tools.range({
        count: { from: 1, to: 2 },
        height: { from: 30, to: 60 },
        rangeX: { from: 80, to: 95 },
        rangeY: { from: 25, to: 75 },
      }),
      tools.range({
        count: { from: 0, to: 3 },
        height: { from: 30, to: 60 },
        rangeX: { from: 80, to: 90 },
        rangeY: { from: 20, to: 80 },
      }),
      tools.strait({
        width: 2,
        direction: 'vertical',
      }),
      tools.strait({ width: 1, direction: 'vertical' }),
      tools.smooth({ power: 3 }),
      tools.through({
        count: { from: 3, to: 4 },
        height: { from: 15, to: 20 },
        rangeX: { from: 15, to: 85 },
        rangeY: { from: 20, to: 80 },
      }),
      tools.through({
        count: { from: 3, to: 4 },
        height: { from: 5, to: 10 },
        rangeX: { from: 45, to: 55 },
        rangeY: { from: 45, to: 55 },
      }),
      tools.pit({
        count: { from: 3, to: 4 },
        height: { from: 10, to: 20 },
        rangeX: { from: 15, to: 85 },
        rangeY: { from: 20, to: 80 },
      }),
      tools.mask({ power: 4 }),
    ],
    probability: 16,
  },
  archipelago: {
    id: 4,
    name: 'Archipelago',
    steps: [
      tools.add({ add: 11, range: 'all' }),
      tools.range({
        count: { from: 2, to: 3 },
        height: { from: 40, to: 60 },
        rangeX: { from: 20, to: 80 },
        rangeY: { from: 20, to: 80 },
      }),
      tools.hill({
        count: 5,
        height: { from: 15, to: 20 },
        rangeX: { from: 10, to: 90 },
        rangeY: { from: 30, to: 70 },
      }),
      tools.hill({
        count: 2,
        height: { from: 10, to: 15 },
        rangeX: { from: 10, to: 30 },
        rangeY: { from: 20, to: 80 },
      }),
      tools.hill({
        count: 2,
        height: { from: 10, to: 15 },
        rangeX: { from: 60, to: 90 },
        rangeY: { from: 20, to: 80 },
      }),
      tools.smooth({ power: 3 }),
      tools.through({
        count: 10,
        height: { from: 20, to: 30 },
        rangeX: { from: 5, to: 95 },
        rangeY: { from: 5, to: 95 },
      }),
      tools.strait({ width: 2, direction: 'vertical' }),
      tools.strait({ width: 2, direction: 'horizontal' }),
      tools.add({ add: 5, range: { from: 0, to: 5 } }),
    ],
    probability: 18,
  },
  atoll: {
    id: 5,
    name: 'Atoll',
    steps: [
      tools.hill({
        count: 1,
        height: { from: 75, to: 80 },
        rangeX: { from: 50, to: 60 },
        rangeY: { from: 45, to: 55 },
      }),
      tools.hill({
        count: 1.5,
        height: { from: 30, to: 50 },
        rangeX: { from: 25, to: 75 },
        rangeY: { from: 30, to: 70 },
      }),
      tools.hill({
        count: 0.5,
        height: { from: 30, to: 50 },
        rangeX: { from: 25, to: 35 },
        rangeY: { from: 30, to: 70 },
      }),
      tools.smooth({ power: 1 }),
      tools.multiply({
        multiplier: 0.2,
        range: { from: 25, to: 100 },
      }),
      tools.hill({
        count: 0.5,
        height: { from: 10, to: 20 },
        rangeX: { from: 50, to: 55 },
        rangeY: { from: 48, to: 52 },
      }),
    ],
    probability: 1,
  },
  mediterranean: {
    id: 6,
    name: 'Mediterranean',
    steps: [
      tools.range({
        count: { from: 4, to: 6 },
        height: { from: 30, to: 80 },
        rangeX: { from: 0, to: 100 },
        rangeY: { from: 0, to: 10 },
      }),
      tools.range({
        count: { from: 4, to: 6 },
        height: { from: 30, to: 80 },
        rangeX: { from: 0, to: 100 },
        rangeY: { from: 90, to: 100 },
      }),
      tools.hill({
        count: { from: 6, to: 8 },
        height: { from: 30, to: 50 },
        rangeX: { from: 10, to: 90 },
        rangeY: { from: 0, to: 5 },
      }),
      tools.hill({
        count: { from: 6, to: 8 },
        height: { from: 30, to: 50 },
        rangeX: { from: 10, to: 90 },
        rangeY: { from: 95, to: 100 },
      }),
      tools.multiply({ multiplier: 0.9, range: 'land' }),
      tools.mask({ power: -2 }),
      tools.smooth({ power: 1 }),
      tools.hill({
        count: { from: 2, to: 3 },
        height: { from: 30, to: 70 },
        rangeX: { from: 0, to: 5 },
        rangeY: { from: 20, to: 80 },
      }),
      tools.hill({
        count: { from: 2, to: 3 },
        height: { from: 30, to: 70 },
        rangeX: { from: 95, to: 100 },
        rangeY: { from: 20, to: 80 },
      }),
      tools.through({
        count: { from: 3, to: 5 },
        height: { from: 40, to: 50 },
        rangeX: { from: 0, to: 100 },
        rangeY: { from: 0, to: 10 },
      }),
      tools.through({
        count: { from: 3, to: 5 },
        height: { from: 40, to: 50 },
        rangeX: { from: 0, to: 100 },
        rangeY: { from: 90, to: 100 },
      }),
    ],
    probability: 5,
  },
  peninsula: {
    id: 7,
    name: 'Peninsula',
    steps: [
      tools.range({
        count: { from: 2, to: 3 },
        height: { from: 20, to: 35 },
        rangeX: { from: 40, to: 50 },
        rangeY: { from: 0, to: 15 },
      }),
      tools.add({ add: 5, range: 'all' }),
      tools.hill({
        count: 1,
        height: { from: 90, to: 100 },
        rangeX: { from: 10, to: 90 },
        rangeY: { from: 0, to: 5 },
      }),
      tools.add({ add: 13, range: 'all' }),
      tools.hill({
        count: { from: 3, to: 4 },
        height: { from: 3, to: 5 },
        rangeX: { from: 5, to: 95 },
        rangeY: { from: 80, to: 100 },
      }),
      tools.hill({
        count: { from: 1, to: 2 },
        height: { from: 3, to: 5 },
        rangeX: { from: 5, to: 95 },
        rangeY: { from: 40, to: 60 },
      }),
      tools.through({
        count: { from: 5, to: 6 },
        height: { from: 10, to: 25 },
        rangeX: { from: 5, to: 95 },
        rangeY: { from: 5, to: 95 },
      }),
      tools.smooth({ power: 3 }),
      tools.invert({ count: 0.4, axes: 'both' }),
    ],
    probability: 3,
  },
  pangea: {
    id: 8,
    name: 'Pangea',
    steps: [
      tools.hill({
        count: { from: 1, to: 2 },
        height: { from: 25, to: 40 },
        rangeX: { from: 15, to: 50 },
        rangeY: { from: 0, to: 10 },
      }),
      tools.hill({
        count: { from: 1, to: 2 },
        height: { from: 5, to: 40 },
        rangeX: { from: 50, to: 85 },
        rangeY: { from: 0, to: 10 },
      }),
      tools.hill({
        count: { from: 1, to: 2 },
        height: { from: 25, to: 40 },
        rangeX: { from: 50, to: 85 },
        rangeY: { from: 90, to: 100 },
      }),
      tools.hill({
        count: { from: 1, to: 2 },
        height: { from: 5, to: 40 },
        rangeX: { from: 15, to: 50 },
        rangeY: { from: 90, to: 100 },
      }),
      tools.hill({
        count: { from: 8, to: 12 },
        height: { from: 20, to: 40 },
        rangeX: { from: 20, to: 80 },
        rangeY: { from: 48, to: 52 },
      }),
      tools.smooth({ power: 2 }),
      tools.multiply({ multiplier: 0.7, range: 'land' }),
      tools.through({
        count: { from: 3, to: 4 },
        height: { from: 25, to: 35 },
        rangeX: { from: 5, to: 95 },
        rangeY: { from: 10, to: 20 },
      }),
      tools.through({
        count: { from: 3, to: 4 },
        height: { from: 25, to: 35 },
        rangeX: { from: 5, to: 95 },
        rangeY: { from: 80, to: 90 },
      }),
      tools.range({
        count: { from: 5, to: 6 },
        height: { from: 30, to: 40 },
        rangeX: { from: 10, to: 90 },
        rangeY: { from: 35, to: 65 },
      }),
    ],
    probability: 5,
  },
  isthmus: {
    id: 9,
    name: 'Isthmus',
    steps: [
      tools.hill({
        count: { from: 5, to: 10 },
        height: { from: 15, to: 30 },
        rangeX: { from: 0, to: 30 },
        rangeY: { from: 0, to: 20 },
      }),
      tools.hill({
        count: { from: 5, to: 10 },
        height: { from: 15, to: 30 },
        rangeX: { from: 10, to: 50 },
        rangeY: { from: 20, to: 40 },
      }),
      tools.hill({
        count: { from: 5, to: 10 },
        height: { from: 15, to: 30 },
        rangeX: { from: 30, to: 70 },
        rangeY: { from: 40, to: 60 },
      }),
      tools.hill({
        count: { from: 5, to: 10 },
        height: { from: 15, to: 30 },
        rangeX: { from: 50, to: 90 },
        rangeY: { from: 60, to: 80 },
      }),
      tools.hill({
        count: { from: 5, to: 10 },
        height: { from: 15, to: 30 },
        rangeX: { from: 70, to: 100 },
        rangeY: { from: 80, to: 100 },
      }),
      tools.smooth({ power: 2 }),
      tools.through({
        count: 4 - 8,
        height: { from: 15, to: 30 },
        rangeX: { from: 0, to: 30 },
        rangeY: { from: 0, to: 20 },
      }),
      tools.through({
        count: 4 - 8,
        height: { from: 15, to: 30 },
        rangeX: { from: 10, to: 50 },
        rangeY: { from: 20, to: 40 },
      }),
      tools.through({
        count: 4 - 8,
        height: { from: 15, to: 30 },
        rangeX: { from: 30, to: 70 },
        rangeY: { from: 40, to: 60 },
      }),
      tools.through({
        count: 4 - 8,
        height: { from: 15, to: 30 },
        rangeX: { from: 50, to: 90 },
        rangeY: { from: 60, to: 80 },
      }),
      tools.through({
        count: 4 - 8,
        height: { from: 15, to: 30 },
        rangeX: { from: 70, to: 100 },
        rangeY: { from: 80, to: 100 },
      }),
      tools.invert({ count: 0.25, axes: 'x' }),
    ],
    probability: 2,
  },
  shattered: {
    id: 10,
    name: 'Shattered',
    steps: [
      tools.hill({
        count: 8,
        height: { from: 35, to: 40 },
        rangeX: { from: 15, to: 85 },
        rangeY: { from: 30, to: 70 },
      }),
      tools.through({
        count: { from: 10, to: 20 },
        height: { from: 40, to: 50 },
        rangeX: { from: 5, to: 95 },
        rangeY: { from: 5, to: 95 },
      }),
      tools.range({
        count: { from: 5, to: 7 },
        height: { from: 30, to: 40 },
        rangeX: { from: 10, to: 90 },
        rangeY: { from: 20, to: 80 },
      }),
      tools.pit({
        count: { from: 12, to: 20 },
        height: { from: 30, to: 40 },
        rangeX: { from: 15, to: 85 },
        rangeY: { from: 20, to: 80 },
      }),
    ],
    probability: 7,
  },
  taklamakan: {
    id: 11,
    name: 'Taklamakan',
    steps: [
      tools.hill({
        count: { from: 1, to: 3 },
        height: { from: 20, to: 30 },
        rangeX: { from: 30, to: 70 },
        rangeY: { from: 30, to: 70 },
      }),
      tools.hill({
        count: { from: 2, to: 4 },
        height: { from: 60, to: 85 },
        rangeX: { from: 0, to: 5 },
        rangeY: { from: 0, to: 100 },
      }),
      tools.hill({
        count: { from: 2, to: 4 },
        height: { from: 60, to: 85 },
        rangeX: { from: 95, to: 100 },
        rangeY: { from: 0, to: 100 },
      }),
      tools.hill({
        count: { from: 3, to: 4 },
        height: { from: 60, to: 85 },
        rangeX: { from: 20, to: 80 },
        rangeY: { from: 0, to: 5 },
      }),
      tools.hill({
        count: { from: 3, to: 4 },
        height: { from: 60, to: 85 },
        rangeX: { from: 20, to: 80 },
        rangeY: { from: 95, to: 100 },
      }),
      tools.smooth({ power: 3 }),
    ],
    probability: 1,
  },
  oldWorld: {
    id: 12,
    name: 'Old World',
    steps: [
      tools.range({
        count: 3,
        height: 70,
        rangeX: { from: 15, to: 85 },
        rangeY: { from: 20, to: 80 },
      }),
      tools.hill({
        count: { from: 2, to: 3 },
        height: { from: 50, to: 70 },
        rangeX: { from: 15, to: 45 },
        rangeY: { from: 20, to: 80 },
      }),
      tools.hill({
        count: { from: 2, to: 3 },
        height: { from: 50, to: 70 },
        rangeX: { from: 65, to: 85 },
        rangeY: { from: 20, to: 80 },
      }),
      tools.hill({
        count: { from: 4, to: 6 },
        height: { from: 20, to: 25 },
        rangeX: { from: 15, to: 85 },
        rangeY: { from: 20, to: 80 },
      }),
      tools.multiply({ multiplier: 0.5, range: 'land' }),
      tools.smooth({ power: 2 }),
      tools.range({
        count: { from: 3, to: 4 },
        height: { from: 20, to: 50 },
        rangeX: { from: 15, to: 35 },
        rangeY: { from: 20, to: 45 },
      }),
      tools.range({
        count: { from: 2, to: 4 },
        height: { from: 20, to: 50 },
        rangeX: { from: 65, to: 85 },
        rangeY: { from: 45, to: 80 },
      }),
      tools.strait({
        width: { from: 3, to: 7 },
        direction: 'vertical',
      }),
      tools.through({
        count: { from: 6, to: 8 },
        height: { from: 20, to: 50 },
        rangeX: { from: 15, to: 85 },
        rangeY: { from: 45, to: 65 },
      }),
      tools.pit({
        count: { from: 5, to: 6 },
        height: { from: 20, to: 30 },
        rangeX: { from: 10, to: 90 },
        rangeY: { from: 10, to: 90 },
      }),
    ],
    probability: 8,
  },
  fractious: {
    id: 13,
    name: 'Fractious',
    steps: [
      tools.hill({
        count: { from: 12, to: 15 },
        height: { from: 50, to: 80 },
        rangeX: { from: 5, to: 95 },
        rangeY: { from: 5, to: 95 },
      }),
      tools.mask({ power: -1.5 }),
      tools.mask({ power: 3 }),
      tools.add({ add: -20, range: { from: 30, to: 100 } }),
      tools.range({
        count: { from: 6, to: 8 },
        height: { from: 40, to: 50 },
        rangeX: { from: 5, to: 95 },
        rangeY: { from: 10, to: 90 },
      }),
    ],
    probability: 3,
  },
};
