/**
 * A point on a 2D plane, utility type.
 */
export type Point = [number, number];

/**
 * Voronoi cell generated from the voronoi algorithm.
 */
export interface Cell {
  /**
   * Cell vertices for the cell.
   */
  vertices: number[];

  /**
   * Index of the cells adjacent to the cell.
   */
  adjacentCells: number[];

  /**
   * Tells if the cell is a near border cell or not.
   */
  isNearBorder: boolean;
}

/**
 * Vertex identifying a point on a cell and all its relevant data.
 */
export interface Vertex {
  /**
   * Coordinates for the vertex of a cell, will be set to the center of the triangle generated by delaunator.
   */
  coordinates: Point;

  /**
   * Neighbouring vertices for the vertex.
   */
  neighbours: number[];

  /**
   * Adjacent cells of the vertex.
   */
  adjacent: [number, number, number];
}

/**
 * The definition for a map's Grid, which contains all the cells and vertices definitions.
 */
export interface Grid {
  spacing: number;
  boundary: Point[];
  points: Point[];
  cellsX: number;
  cellsY: number;

  cells: Cell[];
  vertices: Vertex[];
}
